.eslintrc.json, package-lock.json, package.json, src/App.js
<aside>
💻 **pr 템플릿**
- 체크리스트
- eslint 추가
- dependency 파일 설치 필요
=> build: eslint 추가

eslint.config.mjs, package-lock.json, package.json, tsconfig.json
<aside>
💻 **pr 템플릿**
- 체크리스트
- eslint 재설정
=> Build: eslint 설정

.prettierrc, package-lock.json, package.json
<aside>
💻 **pr 템플릿**
- 체크리스트
-  prettier 초기설정
=> Build: prettier 초기설정

package-lock.json, package.json
=> [Chore] package 이름 변경(project_setting -> travelport)

.prettierrc, package-lock.json
- prettier 옵션 추가
- endOfLine : auto => OS별 자동으로 설정
- package-lock.json 변경
- 업데이트에 따른 버전 일부 업데이트
-
=> [Setting] prettier 속성 추가(LF, CRLF auto 설정) 및 package 업데이트

src/assets/images.d.ts, tsconfig.json
- image 파일 import를 위한 설정 추가
- png, svg, jpg, jpeg 추가
- 관련 tsconfig 내용 수정
- 추후 다른 종류의 image 파일을 추가하려고 하는 경우 `declare module '(.확장자명)';` 형식으로 images.d.ts에 추가해주시면 됩니다.
=> [Feat] image 파일 import를 위한 설정 추가

src/components/myPage/EditPartnerInfo.tsx, src/components/myPage/EditUserInfo.tsx, src/components/myPage/MyPageSideBar.tsx, src/pages/MyPage.tsx, src/utils/zustand.ts
- 파트너 정보수정 페이지 기능 구현
- 사이드바 기능구현
- 전역 상태를 통한 유저 데이터 관리
- 전역 상태 관리 안정성을 위한 zustand 사용법 개선
- 추후 멘토링 중 나온 react query 등 유저 데이터 캐싱 방향 고려 중
=> [Refactor] 파트너 정보 수정 페이지 구현 및 사이드바 기능 구현

package-lock.json, src/components/common/Button.tsx, src/components/common/InputBox.tsx, src/components/common/TextBox.tsx, src/pages/auth/login/Login.tsx, src/pages/auth/signup/PartnerSignup.tsx, src/pages/auth/signup/UserSignup.tsx, src/styles/reset.css, tailwind.config.js
- font 내 기본값에 'plex_sansKR' 우선 추가
- 컴포넌트(InputBox, TextBox, Button) 및 로그인, 회원가입 페이지에 해당 기본값 반영
- reset.css -> border 기본 설정 값 변경
- package-lock 일부 변경 내용 반영
- 크기 단위(px,rem) 단위 관련 통일성 부여
-
=> [Design] font 기본값 설정 변경, css 설정 변경 내용 적용

src/pages/auth/login/Login.tsx, src/pages/auth/signup/PartnerSignup.tsx, src/pages/auth/signup/UserSignup.tsx
- (회원가입) 이메일 중복확인 기능 관련 api 연결
- 로그인, 회원가입 하기 기능 관련 api 연결
- test@test.com 입력 시 400 error가 나오는 문제가 있습니다.
- 이미 가입 된 이메일로 추정
- 이유 : 해당 계정으로 로그인 시도 시, 정상 로그인 진행 되는 것을 확인(아닌 것은 401 error로 나오면서 로그인 x)
- 추후 해당 에러에 맞춰 '이메일이 중복됩니다'등의 기능이 연결되도록 수정할 예정입니다.
- 이메일로 로그인시 refresh token이 발급되지 않고 accessToken만 발급되어 cookie에 저장됩니다.
**<중복 확인 True>**
=> [Feat] 중복확인, 회원가입, 로그인 API 1차 연결

src/apis/productAll.ts, src/apis/review.ts, src/components/common/SearchBar.tsx, src/components/common/headerBar/HeaderBar.tsx, src/constants/types.ts, src/hooks/useProductAll.ts, src/hooks/useScoreAvg.ts, src/hooks/useSearchData.ts, src/pages/List.tsx, src/utils/getMinPrice.ts, src/utils/uniqueProduct.ts
- list page 검색어-카드-api 연결
- 검색: 상품 이름, 상품 위치(productAddress)로 검색 가능
- useProductAll 훅 생성 : 전체 product, option data 불러옴
- useScoreAve 훅 생성 : 평점, 리뷰 수 리턴
- uniqueProduct 함수 : 하나의 product에서 여러 개의 옵션이 있을 때 하나만 받아오는 로직 구현
- getMinPrice 함수 : 여러 옵션의 가격 중 최소값 리턴
- 필요하면 함수&훅&타입 갖다 쓰세요!
=> [Feat] 카드 연결에 필요한 hooks & util 함수 구현

src/apis/auth.ts, src/apis/editInfo.ts, src/components/myPage/ChangePassword.tsx, src/components/myPage/EditInfo.tsx, src/components/myPage/MyPageSideBar.tsx, src/utils/axios.ts, src/utils/jwtDecode.ts, src/utils/zustand.ts
- 정보 수정 api 연결
- 비밀번호 변경 api 연결
- 쿠키 첨부 이슈 수정
- 아직 토큰 일부가 안받아와지는 이슈가 있음 주의
=> [Refactor & Fix] 정보 수정, 비밀번호 변경 api 연결 및 토큰 첨부 에러 수정

src/components/review/ReviewAverage.tsx
- Review Average 컴포넌트 구현
- 리뷰를 작성한 총 인원에 대한 별점 분포 표시
- 평균 평점 표시
-
=> [Feat] Review Average 컴포넌트 구현

src/components/common/Button.tsx, src/pages/auth/login/GoogleRedirect.tsx, src/pages/auth/login/KakaoRedirect.tsx, src/pages/auth/login/Login.tsx, src/pages/auth/login/NaverRedirect.tsx, src/pages/auth/signup/PartnerSignup.tsx, src/pages/auth/signup/UserSignup.tsx, src/utils/cookie.ts
- Button 컴포넌트 : buttonType prop 추가
- submit, button, reset
- 로그인, 회원가입 버튼 -> submit 타입으로 변경
- email, pw 입력 후 enter 키보드 입력 시, 정상 동작 가능
- accessToken 저장 issue 해결 및 새로 고침 시 cookie가 사라지던 문제 해결
- path 설정 및 유효기간 설정
- 일부 환경에서 refreshToken이 나오지 않는 문제가 아직 존재합니다.
- close-#45
=> [Feat] accessToken cookie 저장 및 새로고침 시 지워지는 문제 해결, Button 컴포넌트 type 관련 props 추가

src/components/SearchResultPagination.tsx, src/components/SearchResultSection.tsx, src/hooks/useDispalyControl.ts, src/hooks/useProductsWithMinPrice.ts, src/pages/Main.tsx, src/pages/ReviewRegist.tsx, src/pages/SearchResultPage.tsx
- 검색 결과 페이지 카드 컴포넌트로 분리 
- 카테고리 버튼 구현 완료
- 필터링 버튼 스타일 변경 완료
- 화면 크기에 따라 카드 렌더링 커스텀 훅으로 구현 
- 페이지네이션 적용
- 무한 렌더링 버그 useMemo로 해결
-
=> [Feat] 검색 결과 페이지 구현 완료 

src/components/Pay.tsx, src/components/SearchResultSection.tsx, src/components/common/FilterButton.tsx, src/components/common/headerBar/HeaderBar.tsx, src/components/common/headerBar/LoginUserHeaderBar.tsx, src/hooks/useFilterByCategory.ts, src/hooks/useFilterProducts.ts, src/hooks/usePaymentWidget.ts, src/hooks/useProductOptionsReviews.ts, src/hooks/useProductsWithMinPrice.ts, src/pages/Main.tsx, src/pages/SearchResultPage.tsx, src/pages/payments/CheckoutPage.tsx
- 결제 구현 컴포넌트 분리
- 유저랑 파트너 장바구니 다르게 보이게 수정
- 필터링 훅 빼기
- 필터링 버튼 컴포넌트 분리 
- 경로 전부 수정
- option에 productOptions 추가
- destroy is not a function 에러 해결
- 백엔드 쪽에서 optionAll 데이터를 수정해서 보내셨더라구요, 그거에 맞게 수정 했습니다 
=> [Feat] 바뀐 데이터 경로 수정 및 필터링 훅, 필터링 버튼 컴포넌트 구현 

src/assets/icons/arrowDown.svg, src/assets/icons/minusActive.svg, src/assets/icons/minusInactive.svg, src/assets/icons/plusActive.svg, src/assets/icons/plusInactive.svg, src/assets/icons/search.svg, src/components/common/CalendarCustom.css, src/components/common/card/Card.tsx, src/components/common/card/HotelCard.tsx, src/components/common/filter/HeadCount.tsx, src/components/common/filter/PriceRange.tsx, src/components/common/filter/ProductType.tsx, src/hooks/reactQuery/product/useProductAll.ts, src/hooks/useScoreAvg.ts, src/pages/List.tsx, src/styles/PriceRange.css
- 숙소용 카드 컴포넌트 구현
- 리스트페이지 필터링 UI 구현
- 날짜 필터링
- 인원수 필터링
- 가격대 필터링
- 종류 필터링
- url, 필터링 기능, 페이지네이션 연결 작업 예정
=> [Feat] list page

src/App.tsx, src/components/PartnerMainButton.tsx, src/components/common/headerBar/LoginUserHeaderBar.tsx, src/components/myPage/EditInfo.tsx, src/components/myPage/MyPageButton.tsx, src/components/myPage/MyPageSideBar.tsx, src/constants/types.ts, src/pages/MyPage.tsx, src/pages/PartnerMain.tsx, src/utils/jwtDecode.ts, src/utils/zustand.ts
- 사용자, 파트너 마이페이지 분리
- useParams를 이용한 마이페이지 경로 재구성
- 파트너 메인페이지 구현
=> [Feat & Refactor] 마이페이지 라우트 재설정 및 파트너 메인페이지 구현

src/assets/icons/search-pr.svg, src/components/common/InputBox.tsx, src/components/common/NumberInputBox.tsx, src/components/common/map/PostCode.tsx, src/pages/productRegist/Category.tsx, src/pages/productRegist/Description.tsx, src/pages/productRegist/Option.tsx
- input, textarea 이슈 -> 기본 input과 textarea는 직접 작성 / NumberInput 컴포넌트를 생성하여 input타입이 number인 기능들 구현
- description페이지 기초 구현
- Option페이지 기초 구현
- Option페이지 디자인 수정 필요
- close-#91
=> [Feat] NumberInput 컴포넌트 구현, description페이지와 Option페이지 기초구현

src/components/MainCard.tsx, src/components/SearchResultSection.tsx, src/components/common/SearchBar.tsx, src/components/common/headerBar/LoginUserHeaderBar.tsx, src/hooks/reactQuery/reservation/useReservationMutation.ts, src/hooks/useFilterByCategory.ts, src/hooks/useFilterProducts.ts, src/hooks/useProductsWithMinPrice.ts, src/pages/Main.tsx, src/pages/SearchResultPage.tsx, src/pages/payments/CheckoutPage.tsx, src/pages/payments/SuccessPage.tsx
- 변경된 api로 코드 전면 수정
- 서치바 && 추가
- product, productOption, review 계산 공식 제거 
- 헤더 드롭다운, 사이드바 경로 수정
- 결제할때 필요한 api 수정 및 예약 zustand store 가져와서 사용
-
- 데이터가 다 날아가서 스크린샷을 찍을 수가 없습니다. 
=> [Refactor] 수정된 api에 맞게 메인, 검색결과, 결제페이지 코드 수정 

src/App.tsx, src/components/CartList.tsx, src/pages/Cart.tsx
- 장바구니 페이지 생성
- 장바구니 디자인 구현
- CartList 컴포넌트 분리
- api가 아직 제대로 구현이 안되어 있어서 api 연결은 추후에 하도록 하겠습니다 !
---
--- 
=> [UI] 장바구니 페이지 UI 구현

src/App.tsx, src/apis/image.ts, src/assets/icons/x-circle-custom.svg, src/components/MainCard.tsx, src/components/ReservedManageCard.tsx, src/components/SearchResultSection.tsx, src/components/common/card/CardSample.tsx, src/components/common/card/HotelCard.tsx, src/components/common/filter/ProductType.tsx, src/components/common/headerBar/HeaderBar.tsx, src/components/common/headerBar/LoginUserHeaderBar.tsx, src/components/common/layout/Layout.tsx, src/components/common/reservPagination/ResevationCard.tsx, src/components/details/Reservation.tsx, src/components/myPage/EditInfo.tsx, src/components/myPage/MyResevation.tsx, src/components/myPage/ReservButton.tsx, src/pages/Main.tsx, src/pages/MyPage.tsx, src/pages/ReviewRegist.tsx, src/pages/productRegist/Category.tsx, src/pages/productRegist/ProductRegist.tsx, src/utils/axios.ts
- [버튼 컴포넌트의 상태에 따른 로직 재구성](https://github.com/sprint4-part4-team7/TravelPort-49105/commit/03cea50ed46768df887c0267009893416101668f)
- [프로필 이미지 등록 해제 기능 추가](https://github.com/sprint4-part4-team7/TravelPort-49105/commit/53b532af814afb6022b83443541fd1eac52b07fb)
- [예약 관리 데이터 표시에 맞춰 예약 현황 양식 조정](https://github.com/sprint4-part4-team7/TravelPort-49105/commit/06098ac07253ff54f66192a96e42a95a6305007a)
- 추후 예약 데이터에 판매자 정보 추가될 시 예약 현황, 관리 ui 개선 필요 (영훈)
=> [Refactor] 프로필 이미지 업로드 및 예약 버튼 로직 개선

src/components/CartList.tsx, src/components/MainCategoryButton.tsx, src/components/common/headerBar/HeaderBar.tsx, src/components/details/Reservation.tsx, src/hooks/reactQuery/cart/useCartReservationByUserIdMutation.ts, src/hooks/reactQuery/reservation/useReservationMutation.ts, src/pages/payments/CheckoutPage.tsx, src/pages/payments/SuccessPage.tsx, src/utils/zustand.ts
- 헤더바 바능형 완료
- Reservation.tsx option 에러 해결 
- 결제 페이지 에러 해결 
- 검색 결과 페이지 헤더 서치바 길이 조정 
- cartInfo 없을때 일반 결제 진행 
- Reservation.tsx cart api 2번 호출  -> 1번 호출로 변경 
-
=> [Refactor] 헤더바 반응형 완료

src/apis/reservation.ts, src/components/ReservedManageCard.tsx, src/components/myPage/Modal/RejectReservation.tsx, src/components/myPage/ReservButtonOutlined.tsx, src/pages/PostingManagement.tsx
-예약 거절 메세지 데이터 반영 api(putCancelMsg) 추가
- 게시물 삭제 Modal, 거절 사유 작성 Modal 기능 추가 및 삭제 동작, 거절 사유 작성 내용 반영 확인
- 예약 관리 Card 내 Button 디자인 수정
- 게시물 관리에서 switch를 통한 게시중/게시 중지 상태 및 게시물 삭제가 즉각적으로 반영되지 않는 문제가 있습니다.
**<게시물 삭제 Modal>**
**<거절 사유 작성 Modal>**
**<예약 관리 디자인>**
=> [Feat, Design] 예약 거절 메세지 작성 modal 및 파트너 게시물 작성 modal 구현, 예약 관리 button 디자인 수정

src/components/common/filter/PriceRange.tsx, src/components/review/ReviewStar.tsx
- 리뷰 별점에 cursor: pointer 적용
- 인원수 필터링 시 input에 최소 가격 & 최대 가격 직접 입력 가능하도록 적용
=> [Refactor] 인원수 필터링 직접 입력 안되는 버그 해결

public/index.html, src/components/common/CalendarCustom.tsx, src/components/details/DatePickerCustom.tsx, src/components/details/Reservation.tsx, src/constants/types.ts
- 로그인이 되지 않은 상태에서 결제 / 장바구니 담기 클릭 시 토스트와 함께 로그인페이지로 이동
- 캘린더
- 상품판매 마감날짜 적용
- 오늘 날짜도 선택 가능하도록 수정
https://github.com/sprint4-part4-team7/TravelPort-49105/assets/144013048/c0428153-7c5d-4af1-8781-6823f96ad4d6
=> [Fix] 비로그인 상태에서 결제 / 장바구니 클릭 시 로그인페이지로 이동

src/apis/product.ts, src/hooks/reactQuery/product/useProductPostMutation.ts, src/hooks/reactQuery/product/useProductPutMutation.ts, src/pages/productRegister/Option.tsx, src/utils/zustand.ts
- 기존에 post가 끝까지 안되는 이슈 수정(기존 productOption은 현재 프로젝트와 맞지않으므로 api를 새로 사용)
- 게시 성공시 local 등 남아있는 데이터 모두 삭제
- 게시 성공시 partner 메인페이지로 이동
- 다른분들도 테스트 해보시면 좋을것같아서 css없이 일단 올려둡니다. 있는 버전은 곧 올릴예정입니다.
=> [Feat] post 기능 완성

src/hooks/reactQuery/auth/useSignupMutation.ts, src/index.js, src/pages/auth/signup/PartnerSignup.tsx, src/pages/auth/signup/UserSignup.tsx, src/pages/payments/SuccessPage.tsx
- 회원가입 시 이메일 중복 확인 없이 회원가입 되던 문제 해결
- 이미 가입한 계정에 대한 toast 동작 추가
- 회원가입 시 발생하는 error 에 대한 동작 추가
- Toast 내부 font 굵기 및 text size(16) 설정
-
=> [Fix] 이메일 중복 확인 없이 회원가입 되던 문제 및 회원가입 시 Error 동작 수정, Toast 내부 text 크기 및 font 굵기 수정

src/App.tsx, src/apis/review.ts, src/components/review/ImageUpload.tsx, src/components/review/ReviewStar.tsx, src/constants/types.ts, src/hooks/reactQuery/review/useReviewByReviewIdQuery.ts, src/hooks/useFetchReview.ts, src/hooks/useGetUserIdByReviewId.ts, src/hooks/useProductReview.ts, src/hooks/useReviewDefaults.ts, src/pages/ReviewRegist.tsx, src/pages/ReviewRegister.tsx
- reviewId가 있으면 URL로 넘겨받기
- 리뷰 수정할 때 해당 데이터 불러오기
- 리뷰 데이터가 로그인된 유저가 작성한 것이 아니면 에러 토스트와 함께 메인페이지로 redirect
https://github.com/sprint4-part4-team7/TravelPort-49105/assets/144013048/1fddfc2c-c205-4bcc-aa86-d45c5d10a92a
=> [Feat] 리뷰작성페이지 수정하기 기능 구현

src/hooks/useDatePicker.ts
- 위 에러를 해결하기 위해 useDatePicker() 커스텀 훅 코드 수정 
-
- close #142
=> [fix] destroy에러 해결

src/App.tsx, src/components/myPage/ChangePassword.tsx, src/components/myPage/EditInfo.tsx, src/components/myPage/MyPageSideBar.tsx, src/constants/InputType.ts
- 마이페이지 이슈 수정
- 정보 수정 변경사항 없을 시 저장 버튼 비활성화
- 로그아웃 시 마이페이지 접근 차단
-
=> [Fix] 마이페이지 이슈 수정

src/components/common/card/HotelCard.tsx, src/components/details/Reservation.tsx, src/components/review/ImageUpload.tsx, src/pages/ProductDetails.tsx, src/pages/ReviewRegister.tsx
- 리뷰작성페이지 이미지 업로드 버튼 살림
- 예약페이지에서 연박 시 가격 반영
- 숙박용 카드 UI & 링크 navigate 수정
=> [Refactor] 예약 시 가격, 숙박용 카드

src/components/CartList.tsx, src/hooks/reactQuery/productOption/useProductOptionQuery.ts, src/hooks/reactQuery/timeTable/useTimeTableQuery.ts, src/pages/Cart.tsx, src/pages/payments/CheckoutPage.tsx
- 리액트 훅 쿼리에 refetch 추가
- 값이 nul l또는 undefined일때 refefch함수 실행
-
=> [Fix] 결제페이지, 장바구니 null 뜨는 에러 해결 

src/components/details/DatePickerCustom.tsx, src/components/details/DetailInfo.tsx, src/components/details/Reservation.tsx, src/pages/List.tsx, src/pages/ProductDetails.tsx
- 체험쪽 상세정보 : forEach, map error 해결
- 체험쪽 예약 : 수량선택시 0원 -> 수정 완료
- 리뷰쪽 이미지 안뜸 -> 잘 뜨는 듯 합니다
- 상세상품 상단에 가격에 localeString 처리
- 예약하기 옵션 마감처리 구현 중
=> [refactor] 다양한 에러 해결

src/App.tsx, src/apis/image.ts, src/components/PostingCard.tsx, src/components/ProtectedRoute.tsx, src/components/ReservedManageCard.tsx, src/components/common/layout/Layout.tsx, src/components/myPage/EditInfo.tsx, src/components/myPage/Modal/CancelReserv.tsx, src/components/myPage/MyReservation.tsx, src/components/myPage/ReservChips.tsx, src/constants/reserv.ts, src/constants/types.ts, src/pages/Cart.tsx, src/pages/List.tsx, src/pages/Main.tsx, src/pages/MyPage.tsx, src/pages/PartnerMain.tsx, src/pages/ProductDetails.tsx, src/pages/ReviewRegist.tsx, src/pages/SearchResultPage.tsx, src/pages/payments/CheckoutCartPage.tsx, src/pages/payments/CheckoutPage.tsx, src/utils/axios.ts
- [파트너 메인페이지 길이 이슈 해결 & 레이아웃 푸터 합침](https://github.com/sprint4-part4-team7/TravelPort-49105/commit/60527175bdd5135673f27b6f7c0086502a54860b)
- [파트너 전용 페이지, 사용자 전용 페이지 구분](https://github.com/sprint4-part4-team7/TravelPort-49105/commit/e065d91f143b5515fe220695e14b4f122ea0328d)
- [마이페이지 예약 없을 시 홈화면으로 이어지는 버튼 생성](https://github.com/sprint4-part4-team7/TravelPort-49105/commit/a5ae0154d4815f62de25730139de098f9e82cafe)
- api가 변경되었습니다 확인해주세요
- Layout과 Footer가 합쳐짐에 따라 conflict가 발생할 수 있습니다 이점 유의해주시기 바랍니다
=> [Fix] 마이페이지 이슈 해결 및 api 수정

src/components/common/map/PostCode.tsx, src/pages/auth/login/Login.tsx, src/pages/auth/signup/PartnerSignup.tsx, src/pages/auth/signup/UserSignup.tsx, src/pages/productRegister/Category.tsx, src/pages/productRegister/CheckButton.tsx, src/pages/productRegister/Description.tsx, src/pages/productRegister/Location.tsx, src/pages/productRegister/Option.tsx, src/pages/productRegister/OptionModal.tsx, src/pages/productRegister/ProductRegister.tsx, src/pages/productRegister/productPage.d.ts
- sidebar스타일
- sidebar기능: 페이지에 따라 움직이고, 이미한건 check
- disabled처리: 다 적지않으면 게시못하게, productmodal, productregister전체
- 헤더,푸터 대신 로고: 로고 누르면 파트너 메인페이지로 이동
=> [Feat] sidebar 기능 구현, disabled처리, 메인로고

src/components/details/Reservation.tsx
- 예약하기 페이지 : 일정에 따른 마감 처리 구현
https://github.com/sprint4-part4-team7/TravelPort-49105/assets/144013048/b96bb6a3-176c-4438-976a-59bf75955386
=> [Refactor] 일정에 따른 마감 처리 구현

.eslintrc.json, src/styles/global.css
- searchbar border 색상 변경
- eslint rule 추가
=> [Fix] searchbar border 수정

src/pages/partner/productRegister/DateCheck.tsx, src/pages/partner/productRegister/Description.tsx, src/pages/partner/productRegister/Option.tsx, src/pages/partner/productRegister/OptionModal.tsx
- 아래와 같은 오류 수정
- sidebar 4에서 5넘어갈때 로직 끊김
- 제목->내용->이미지 업로드 진행 후 버튼이 활성화 x(이미지까지 등록 후 내용 혹은 제목이 추가되어야 버튼이 활성화 됨) 
- 숙소 등록 -> 옵션 추가하기 선택 시, 옵션 추가하기 modal(체험)으로 나옴
- 숙소등록 -> 옵션이 다 등록됐을때 시작시간, 종료시간이 없는데 넣을 장소는 있음
- 상품 등록 시 '/partner' 페이지로 이동(아무것도 나오지 않음) ⇒ 일단 main으로 보내
- 백엔드측에서 시간 데이터 타입 받아오는걸 바꿔서, 오류가 뜨지만 상품등록은 정상적으로 가능
=> [Fix] productRegister 오류 수정

src/components/common/layout/headerBar/HeaderBar.tsx, src/pages/user/cart/Cart.tsx, src/pages/user/payments/CheckoutCartPage.tsx, src/pages/user/payments/CheckoutPage.tsx, src/pages/user/payments/SuccessPage.tsx, src/utils/Zustand.ts
- 결제 페이지 몇박인지 작성 
- Cart페이지 key 이슈 해결
- 헤더에 교통 탭 제거
- 장바구니에서 cartApi를 get하면 총 금액(숙소에서 10만원짜리 2박을 선택하면 총금액은 20만원이여야 함)이 나오지 않는 문제 ..
=> [Fix] 결제 페이지 몇박인지 작성 

src/App.tsx, src/apis/productOption.ts, src/apis/review.ts, src/components/common/SearchBar.tsx, src/components/details/Reservation.tsx, src/components/main/Carousel.tsx, src/components/myPage/EditInfo.tsx, src/components/reservation/ManageSearchBar.tsx, src/components/review/ImageUpload.tsx, src/components/review/ReviewStar.tsx, src/hooks/functionHooks/useSearchData.ts, src/hooks/products/useFilterProducts.ts, src/hooks/products/useProductsWithMinPrice.ts, src/pages/MyPage.tsx, src/pages/user/List.tsx, src/pages/user/Main.tsx, src/pages/user/ProductDetails.tsx, src/pages/user/cart/Cart.tsx, src/pages/user/review/ReviewRegister.tsx, src/utils/Cookie.ts
- [마이페이지 헤더바 이슈 & 파트너 메인페이지 이슈 해결](https://github.com/sprint4-part4-team7/TravelPort-49105/commit/51b5bc8605bbf6695d4c073c63f1ad759cfaef6f)
- [불필요한 eslint 무시 룰 전면 제거](https://github.com/sprint4-part4-team7/TravelPort-49105/commit/4b1873cff58bbd72ebea2d0dd214ec9674be05f7)
-
=> [Fix] 불필요한 eslint 삭제 및 마이페이지 헤더 이슈 해결

src/components/cart/CartList.tsx, src/pages/user/cart/Cart.tsx, src/pages/user/payments/CheckoutPage.tsx
- ~몇박 계산하는거 반올림 하기
- 장바구니에는 1박으로 고정
- 
=> [Style] 장바구니에 1박 text 고정

src/components/common/card/Card.tsx, src/components/common/map/KakaoMap.tsx, src/pages/partner/productRegister/ImgModal.tsx, src/pages/partner/productRegister/Location.tsx, src/pages/partner/productRegister/Option.tsx, src/pages/partner/productRegister/productPage.d.ts
- min 1로설정
- timetable 형식에 맞게 수정
- 옵션상세이미지
- 전체 주석처리
-
=> [Fix] min, timetable, 이미지, 전체 주석처리

public/index.html, src/App.tsx, src/components/details/Reservation.tsx, src/components/list/filter/PriceRange.tsx
- 결제하기 뒤로가기 시 ~is not funcation 에러 해결
- 가격대 필터링 시 최소값 마이너스 혹은 NaN일 때 0으로 설정
- remainCount 데이터 없을 때(timetable 생성되지 않음) ticketNum이 무한히 올라가는 것 방지. 0으로 고정함
- 리뷰작성페이지는 파트너가 접근 불가능하도록 설정
-  manifest 에러 해결
=> [Fix] 다양한 에러 해결

src/pages/user/payments/CheckoutCartPage.tsx, src/pages/user/payments/SuccessPage.tsx, src/utils/Zustand.ts
=> [Fix] 장바구니 결제 이슈 해결

src/hooks/auth/useOAuthLogin.ts
=> [Fix] 도메인 설정에 따른 redirect 링크 재설정

src/apis/myReservation.ts, src/components/myPage/MyReservation.tsx, src/constants/Reserv.ts, src/constants/Types.ts
=> [Fix] 예약 취소 안되던 버그 수정

src/components/review/Review.tsx
=> [Fix] 리뷰 프로필 이미지 반영

src/components/review/Review.tsx
=> [Fix] 리뷰 프로필 이미지 최종

src/components/details/Reservation.tsx
- 숙박 & 체험 모두 티켓 수 remainCount까지 올라가는거 확인
-
=> [Fix] 티켓 수 최종

src/components/details/Reservation.tsx, src/hooks/payments/usePaymentWidget.ts
=> [Fix] 결제페이지 selector 에러 해결
