package-lock.json
package.json
src/components/ModalExample.tsx
src/components/common/Modal.tsx

- [twMerge를 통한 모달의 동적 스타일 생성](https://github.com/sprint4-part4-team7/TravelPort-49105/commit/13399808ad405b16a89dca711ad0d733bbaeef3c)
- [모달 esc 닫기 기능, 모달 스크롤 방지 기능 추가](https://github.com/sprint4-part4-team7/TravelPort-49105/commit/d8e5e9194727fa287f4f6d36125c64f182e11da1)
- tailwind css 클래스 병합을 위해 tailwind-merge 라이브러리를 추가했습니다
- 이로인한 npm install이 필요한 점 유의 바랍니다

[Refactor] 모달 공용 컴포넌트 스크롤 방지, esc 닫기 구현 및 모달 커스텀화 추가

---

src/components/common/CalendarCustom.css
src/components/common/CalendarCustom.tsx
src/hooks/useCalendar.ts
src/pages/Reservation.tsx
src/styles/global.css

- useCalendar 훅으로 선택된 date를 받아올 수 있도록 했습니다.
- mockData로 받은 후 로직 구현했습니다.
- 캘린더 width는 CalendarCustom 컴포넌트를 감싼 태그에 설정해주시면 됩니다.
- 디자인 임시로 설정했습니다.
https://github.com/sprint4-part4-team7/TravelPort-49105/assets/144013048/5daa0a5c-5796-41b1-86db-083fa0ca5db6

[Feat] calendar mockdata로 구현

---

tailwind.config.js

- figma 시안에 포함된 color 변수 추가
- blue, black, system, secondary
- black-1 변수의 경우 white(#ffffff) 변수와 같습니다.
- 추후 black의 범위를 수정하거나 white 변수를 삭제하면 되겠습니다.

[Design] figma 시안에 포함된 color 변수 추가

---

src/components/common/TextBox.tsx
src/index.js
src/pages/auth/login/GoogleRedirect.tsx
src/pages/auth/login/KakaoRedirect.tsx
src/pages/auth/login/Login.tsx
src/pages/auth/login/NaverRedirect.tsx
src/utils/cookie.ts

- TextBox 기능 구현 및 디자인 구성
- cookie(react-cookie)관련 함수를 정의한 cookie.ts 파일 정의
- cookie를 활용하기 위해 index.js에 <CookiesProvider> 추가
- Google, Naver, Kakao 소셜 로그인 시, refresh token과 access token을 받는 api 연동
- 소셜 로그인 후 전체적 request가 중복(2번) 요청이 되면서 error가 발생하고 있어 우선 try-catch문으로 error를 임시로 우회하였습니다.
- 백엔드 측에 해당 문제를 이야기하였고, 확인 후 수정 예정입니다.
- kakao의 경우 accessToken이 cookie에 저장되지 않는 문제가 있습니다.
- 혹시 accessToken을 사용해야하는 경우, google, naver를 우선적으로 활용해주시기 바랍니다.
**<TextBox>**
- #45 
- #46

[Feat] TextBox 컴포넌트 기능 구현, Cookie 관련 함수 파일 생성, 소셜 로그인 token 관련 api 연동

---

src/apis/login.ts
src/apis/signup.ts
src/pages/auth/login/GoogleRedirect.tsx
src/pages/auth/login/KakaoRedirect.tsx
src/pages/auth/login/Login.tsx
src/pages/auth/login/NaverRedirect.tsx
src/pages/auth/signup/PartnerSignup.tsx
src/pages/auth/signup/UserSignup.tsx

- apiSample.ts 파일 삭제
- login.ts 파일 생성 및 로그인 api 관련 함수 정의
- POST : 이메일로 로그인 api 함수 정의(postLogin)
- GET : google, kakao, naver 소셜 로그인 api  함수정의(getGoogleLogin, getKakaoLogin, getNaverLogin)
- 페이지 적용 : Login.tsx, 소셜 로그인 별 리다이렉트 페이지
- signup.ts 파일 생성 및 회원가입 api 관련 함수 정의
- POST : 이메일 중복 체크 api 함수 정의(postVerifyEmail)
- POST : 일반 유저, 파트너 유저 회원가입 api 함수 정의(postUserSignup, postPartnerSignup)
- 페이지 적용 : UserSignup.tsx, PartnerSignup.tsx
- 파트너 회원가입의 경우 (/auth/partner-signup) 류의 api가 구현되지 않았기 때문에 파트너 회원가입은 api 구현 전까지는 사용을 피해주시기 바랍니다.
**<이메일 중복체크>**

[Feat, Api] Login, Signup 관련 API 함수 정의 파일 생성, 로그인 및 회원가입 페이지에 함수 적용

---

src/components/Carousel.tsx
src/components/common/Button.tsx
src/components/common/headerBar/UnLoginUserHeaderBar.tsx
src/pages/auth/login/Login.tsx
src/pages/auth/signup/PartnerSignup.tsx
src/pages/auth/signup/UserSignup.tsx

- Figma 시안에 추가 및 변경된 Button 컴포넌트 내용 반영
- 기존에 정의한 Button 컴포넌트 Props 정의 변경
- default 디자인, outlined, floating, 더보기 디자인 구성
- 로그인, 회원가입(유저, 파트너-중복체크 제외), 메인 페이지에 사용되는 Button 요소 -> Button 컴포넌트 적용
- Carousel.tsx, UnLoginUserHeaderBar.tsx에서 사용되던 rem 단위 변경
- 기존 `p-[x rem]` -> `p-x`형식으로 변경
- figma 시안에 제시된 내용 이외에 hover, active 등의 동작 부분에서 추가할만한 내용은 추가하였습니다.
- buttonStyle props 값은 tailwind 형식으로 사용하실 수 있습니다.
- (주의) 버튼 스타일 수정 시(buttonStyle 사용 시), font 굵기, padding, text 크기를 설정 해주셔야 합니다.
- buttonStyle='font-bold' 식으로 사용할 경우, padding, text가 시스템 기본값으로 설정 되기 때문에 font만 변경하더라도 font와 함께 padding, text 값을 추가하셔야합니다.
**<수정된 버튼 구성>**
**<HeaderBar(Mobile)>**
**<HeaderBar(PC, Tablet)>**
**<Carousel>**

[Fix, Design] 공통 Button 컴포넌트 디자인 추가 변경, Button 컴포넌트 적용(로그인, 회원가입, 메인페이지(Header, Carousel))

---

src/pages/productRegist/Category.tsx
src/pages/productRegist/CheckButton.tsx
src/pages/productRegist/ProductRegist.tsx

- CheckButton : 상품등록페이지안에서 페이지 이동을 위한 다음, 게시하기 버튼
- 로컬스토리지 사용하기로 변경되어서 Category 로직 변경
- button에 submit 없음
- 추후 서버가 바뀌면 3->1, 20->2로 변경되어야함

[Feature] checkbutton

---

src/App.tsx
src/components/common/card/Card.tsx
src/components/common/filter/ProductType.tsx
src/components/details/LocationMap.tsx
src/components/details/Reservation.tsx
src/components/details/SalesPeriod.tsx
src/components/review/ImageUpload.tsx
src/constants/month.ts
src/hooks/reactQuery/product/useProductAll.ts
src/hooks/useSearchData.ts
src/hooks/useTimeTable.ts
src/pages/List.tsx
src/pages/ProductDetails.tsx
src/pages/ReviewRegister.tsx
src/styles/PriceRange.css
src/utils/getDate.ts
src/utils/getMinPrice.ts
src/utils/zustand.ts

- 상품 상세 페이지
- 필터에 useOutsideClick 적용
- id값으로 옵션 개별화
- URL 설정 : /details/productId
- 예약하기 클릭 시 예약데이터 zustand 이용하여 보내기
- 리스트 페이지
- 인원수 필터링 UI 개선
- 카드 UI 개선
- 페이지네이션 연결
- categoryId가 1,2일 때 카드 UI 변경
- 리뷰 작성 페이지
- 에러 정상화
- post api 연결
- 사진 업로드 시 삭제 반영
- 예약데이터 보낼 때 timetable의 id를 categoryId에 따라 구분할 필요가 있어 보여 추후 수정하겠습니다.

[Feat] 상품상세, 리스트, 리뷰작성페이지 개선 및 기능 추가

---

src/App.tsx
src/components/ReservedManageCard.tsx
src/components/common/reservPagination/ResevationCard.tsx
src/components/myPage/MyPageSideBar.tsx
src/constants/reserveType.ts
src/pages/MyPage.tsx
src/pages/ReservationManagement.tsx

- reservation API 연결
- 숙박, 체험에 대해 예약한 상품에 대한 정보
- reservationStatus Type 설정 및 관련 동작 구현
- 예약 대기, 예약 승인, 예약 거절, 예약 취소 설정
- 버튼 클릭 시 해당 status에 맞도록 PUT API 연결 및 기능 구현
- 마이페이지(/mypage)의 하위 페이지로 경로 변경
- 기존 /manage 경로 제거
- 파트너 유저가 접속했을 경우에만 동작하도록 설정
- 변경된 경로: /partner/mypage/manage
- ReservationCard 컴포넌트 적용
- 필요한 추가 Props(schedule, user) 추가
- 디자인 일부 수정
- 기타 Refactoring 및 수정 작업
- Sample 파일 삭제
- 현재 거절하기, 승인하기 등의 버튼 클릭 시 바로 변경사항이 반영되지 않을 것인데 새로고침을 할 경우 정상 동작합니다.
- 버튼 클릭 시 변경사항이 바로 적용되도록 적용 예정입니다.

[Feat] 예약 관리 페이지 reservation API 연결, reservationStatus 변경 동작 구현, 경로 변경, 반응형 동작 구현

---

src/components/common/headerBar/LoginUserHeaderBar.tsx
src/components/common/headerBar/UnLoginUserHeaderBar.tsx
src/pages/Main.tsx

- 일반 유저 로그인, 파트너 로그인 시 메인페이지 다르게 보여주기
- 로그아웃 시 userInfo 초기화
- 헤더 파트너 페이지 클릭 시 파트너 회원가입 화면으로 이동 
- 파트너 로그인 시 장바구니 헤더에 안 보이게 구현
- 드롭다운 위치 프로필 이미지 가운데 아래로 조정 
- 로그인 안 했을때 파트너 페이지 클릭 시 파트너 회원가입 쪽으로 이동하게 했는데, 맞을까요? 아니라면 어디로 이동해야 하는지도 알려주세요 😭

[Refactor] 일반 유저 로그인, 파트너 로그인 시 다른 화면 렌더링

---

src/apis/auth.ts
src/components/common/reservPagination/ResevationCard.tsx
src/hooks/reactQuery/auth/useLoginMutation.ts
src/hooks/reactQuery/auth/useSignupMutation.ts
src/hooks/reactQuery/auth/useSocialLoginMutation.ts
src/hooks/reactQuery/auth/useVerifyEmail.ts
src/hooks/useOAuthLogin.ts
src/pages/ReservationManagement.tsx
src/pages/auth/login/GoogleRedirect.tsx
src/pages/auth/login/KakaoRedirect.tsx
src/pages/auth/login/Login.tsx
src/pages/auth/login/NaverRedirect.tsx
src/pages/auth/signup/PartnerSignup.tsx
src/pages/auth/signup/UserSignup.tsx

- 로그인(이메일, 소셜 로그인), 회원가입(일반 유저, 파트너) 관련 React-Query 적용
- 기존 try-catch문에서 custom hook을 생성하여 react query 방식 적용
- 회원가입 API(postSignup) 통합
- 기존 : 일반 유저(USER), 파트너(PARTNER)별 별도의 Signup Method 구성
- 변경 : 하나의 postSignup 구성, data를 받아올 때 loginType까지 설정하도록 설정
- 파트너 회원가입 페이지에서 중복 체크 시, 안내 메세지가 비정상적으로 출력되던 문제 해결
- 정상적으로 회원가입을 하더라도 400 에러가 나오는 문제가 있습니다. 해당 에러는 백엔드의 에러로 보이나, 계정 자체는 정상 생성됩니다.
- 지인님이 지적해주신대로 api를 다시 확인하던 중 흐름상 자연스럽지 않은 부분이 존재하여 수정이 필요해보입니다.

[API] Auth(로그인, 회원가입) React Query 적용 완료, 기타 버그 수정

---

src/App.tsx
src/apis/image.ts
src/apis/product.ts
src/apis/productOption.ts
src/apis/review.ts
src/components/Review.tsx
src/components/common/card/HotelCard.tsx
src/components/common/headerBar/HeaderBar.tsx
src/components/review/ReviewAverage.tsx
src/constants/types.ts
src/hooks/reactQuery/product/useProductByIdQuery.ts
src/hooks/reactQuery/productOption/useProductOptionByProductIdQuery.ts
src/hooks/reactQuery/productOption/useProductOptionQuery.ts
src/hooks/reactQuery/review/useReviewByProductIdQuery.ts
src/hooks/useFetchDetails.ts
src/hooks/useProductReview.ts
src/hooks/useReviewDefaults.ts
src/pages/ProductDetails.tsx
src/pages/ReviewRegist.tsx
src/pages/ReviewRegister.tsx
src/pages/payments/CheckoutPage.tsx
src/utils/uniqueProduct.ts

- 상세페이지
- 리뷰tab과 페이지네이션 연결
- 상세페이지 존재하지 않을 때 404페이지 & 로딩 시 로딩컴포넌트 렌더링
- 헤더&푸터 적용
- 리뷰작성페이지
- api 수정 및 적용
- 경로 수정 : /review/optionId
- 사진 업로드 구현 완성
- 필수 항목(별점, 리뷰 글) 작성 안되어있을 시 등록하기 버튼 비활성
- 헤더&푸터 적용
- 리뷰 사진 업로드하고 일정 시간(1~2분) 지나면 사진 get할 때 file not found error뜹니다.
- 마이페이지 쪽 임시 프로필 구현되면 상세페이지 리뷰 탭에 프로필 불러와지는지 확인 필요합니다.

[Feat] 리뷰작성페이지 완성! 상세페이지 리뷰tab 개선

---

src/apis/product.ts
src/components/ReservedManageCard.tsx
src/components/myPage/MyPageSideBar.tsx
src/hooks/reactQuery/product/useProductByPartnerQuery.ts
src/pages/MyPage.tsx
src/pages/PartnerMain.tsx
src/pages/PostingManagement.tsx
src/pages/ReservationManagement.tsx

- 파트너 게시물 관리 페이지 구현 및 관련 API, Hook 추가
- 페이지 시간순 정렬, 카테고리별 분리 구현
- API : getProductByPartner GET 메서드 추가
- Hook : useProductByPartnerQuery React Query Hook 추가
- 사이드바 항목 추가 및 링크 수정
- 게시물 관리 : /partner/mypage/posting-manage
- 예약 관리 : /partner/mypage/reserve-manage
- 게시물 관리, 예약 관리 페이지 렌더링 관련 문제 해결
- 새로고침 시, 초기에 데이터들이 렌더링 되지 않는 문제 해결
- 예약 승인, 거절 등의 버튼을 눌렀을 때 state가 실시간으로 반영되지 않는 문제 해결
- 파트너 메인 페이지 버튼 별 클릭 시 해당하는 페이지로 링크 설정
- 페이지 디자인은 완성되지 않은 것입니다! 수정 예정이니 디자인은 우선 배제해주세요!
**<상품 게시 관리 페이지>**
**<정렬(최신순)>**
**<정렬(과거순)>**

[Feat, API] 파트너 게시물 관리 페이지 링크 연결, 구현 및 관련 API, hook 추가, 파트너 메인 페이지 내 버튼 클릭 시 링크 이동 추가

---

src/components/myPage/MyResevation.tsx
src/pages/productRegister/Date.tsx

- 이전 머지 오류고침
- datepicker사용해서 시작일, 종료일, 휴무일 전달
- 디자인 순서 변경
- 값이 있어야 abled
- 달력 먼저하고 휴무일이 나중이면 파트너측에서 달력을 2번 봐야해서 순서를 바꿔둠
- datepicker 자체 오류 존재

[Feat] Date기능

---

src/App.tsx
src/components/ProtectedRoute.tsx
src/components/SearchResultSection.tsx
src/pages/Main.tsx

- 디테일 페이지로 가는 경로 수정 
- 로그인 안된 유저가 로그인 하고 봐야할 페이지에 접근 시 메인 페이지로 이동하게 하기
로그인 안된 유저가 로그인 하고 봐야할 페이지에 접근 시에 메인 페이지로 이동해야 하는 페이지가 있다면` <ProtectedRoute> `컴포넌트를 만들어뒀으니,` App.tsx`파일에서 
위 사진처럼 element에 해당 컴포넌트를 ` <ProtectedRoute> `컴포넌트로 감싸주기만 하면 됩니다 !

[Refactor] 디테일 페이지 경로 수정 및 로그인 안된 유저 페이지 겁근 막는 컴포넌트 추가 

---

src/components/OrderSummary.tsx
src/components/SearchResultSection.tsx
src/pages/SearchResultPage.tsx
src/pages/payments/CheckoutPage.tsx
src/pages/payments/SuccessPage.tsx

- 결제 api 안 불러와지는 문제 해결 
- 결제 확인 페이지에서 옵션이름 변경
숙소 -> 00호텔 (4인실)
체험 -> 00체험
- timeTable에 맞게 시간도 변경 
- 검색 결과 페이지 카드 개수 변경 !
https://github.com/sprint4-part4-team7/TravelPort-49105/assets/114905530/d060b3a1-4bc4-467a-bcf9-0127684b194c

[Refactor] 결제 버그 문제 해결 및 결제 페이지 옶션, 시간 알맞게 변경 

---

public/index.html
src/apis/product.ts
src/hooks/reactQuery/product/useProductPostMutation.ts
src/hooks/reactQuery/product/useProductPutMutation.ts
src/pages/productRegister/Category.tsx
src/pages/productRegister/Date.tsx
src/pages/productRegister/Description.tsx
src/pages/productRegister/Option.tsx
src/pages/productRegister/ProductRegister.tsx
src/utils/zustand.ts

- productRegister page 서버로 post하는 기능
(유형선택,하위유형선택,제목,내용,날짜들(시작,종료,휴무),위치정보(위도,경도,주소,빌딩이름) 등 localStorage에 set,get하고 마지막엔 일괄 delete) + (이미지처리 썸네일(미리보기), 옵션이미지(4장)을 zustand로 상태관리해서 전달) + (마지막페이지인 옵션에서 받은 옵션사진,상품명,상품설명,가격,인원,갯수,시작시간,종료시간을 useState로 받아서 관리) => 전부 서버로 전송
- categoryType 일관성을 위해 수정
- Datepicker 파트너 입장을 고려하기 위해 수정
- 옵션 체험은 만들었는데, 숙소는 미구현(몇가지 로직만 없애면 되는 간단한작업)
- 아직 모든 css를 구현하진 못함
- 순서가 있는페이지여서 순차적으로 진행되어야 하는데, date쪽에서 문제가 있어서 아마 제대로 동작하지 않을 것(백엔드측을 기다려야함) -> date쪽에서 post해서 받아올때 sql관련한 오류
- date오류를 해결하기 위해 시도한 코드들(다 실패)

[Feat] Post기능

---

src/pages/payments/CheckoutPage.tsx

- 상품상세에서 결제를 누르면 개수 부분 bug 해결
-
https://github.com/sprint4-part4-team7/TravelPort-49105/assets/114905530/bf36cce4-d0c3-4852-9224-8191a326337c
close #130

[fix] 결제 count 버그 해결

---

src/components/common/headerBar/LoginUserHeaderBar.tsx
src/pages/payments/SuccessPage.tsx

- 헤더바 및 결제 완료 페이지에서 나오는 결제 내역, 결제 현황 보러가는 경로 수정
- 결제 페이지 reservation api 두번 요청되는 이슈 해결 
-

[Fix] 결제 페이지 reservation api 두번 요청되는 이슈 해결 

---

src/components/PostingCard.tsx
src/components/ReservedManageCard.tsx
src/components/myPage/Modal/DeletePosting.tsx
src/hooks/reactQuery/product/usePostingStateMutation.ts
src/hooks/reactQuery/product/useProductDeleteMutation.ts
src/pages/PostingManagement.tsx

- 게시물 관리
- switch on/off 및 삭제하기 동작 후 내용이 자동으로 refetch되어 렌더링이 바로 반영되도록 변경
- 게시물 card 클릭 시 페이지 이동(현재 : /partner/product-register)
- (현재 비활성화) 새 게시물 등록 버튼 기능 구현
- 예약 관리
- 예약 거절 시, '취소하기' 버튼 삭제
- 예약 관리 시, dependency array 관련 오류 일부 수정
- 추후 카드 클릭 시 해당 게시물을 편집하는 페이지로 이동할 수 있도록 변경 예정입니다.

[Fix] switch on/off, 삭제하기 동작 후 내용이 바로 반영되도록 수정, 예약 관리-예약 거절 시 '취소하기' 버튼 삭제 외
